"""add payment tracking fields

Revision ID: 0466e1dc54ce
Revises: make_first_user_super_admin
Create Date: 2026-06-03 19:22:44.812664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0466e1dc54ce'
down_revision: Union[str, Sequence[str], None] = 'make_first_user_super_admin'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('subscriptions', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_unique_constraint(None, 'subscriptions', ['stripe_session_id'])
    op.create_unique_constraint(None, 'subscriptions', ['stripe_payment_intent_id'])
    op.create_unique_constraint(None, 'subscriptions', ['razorpay_payment_id'])
    op.create_unique_constraint(None, 'subscriptions', ['razorpay_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscriptions', 'credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscriptions', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'stripe_payment_intent_id')
    op.drop_column('subscriptions', 'stripe_session_id')
    op.drop_column('subscriptions', 'razorpay_payment_id')
    op.drop_column('subscriptions', 'razorpay_order_id')
    # ### end Alembic commands ###
