"""add document column to tasks

Revision ID: 650a1026389e
Revises: 3b7c2d9e1f40
Create Date: 2026-05-12 15:07:09.026239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650a1026389e'
down_revision: Union[str, Sequence[str], None] = '3b7c2d9e1f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_history', 'approval_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('approval_history', 'action_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('approval_history', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_approval_history_id'), 'approval_history', ['id'], unique=False)
    op.alter_column('approvals', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('approvals', 'requested_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('approvals', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('approvals', 'current_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('task_history', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_history', 'old_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task_history', 'new_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task_history', 'changed_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'task_history', 'users', ['changed_by'], ['id'])
    op.create_foreign_key(None, 'task_history', 'tasks', ['task_id'], ['id'])
    op.add_column('tasks', sa.Column('document', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'document')
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.alter_column('task_history', 'changed_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_history', 'new_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_history', 'old_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_history', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.alter_column('approvals', 'current_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('approvals', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('approvals', 'requested_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('approvals', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_approval_history_id'), table_name='approval_history')
    op.alter_column('approval_history', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('approval_history', 'action_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('approval_history', 'approval_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
