"""initial_schema

Revision ID: e797ddd817dd
Revises: 
Create Date: 2026-06-25 14:44:23.168431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e797ddd817dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_organization_status', 'organizations', ['status'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id'),
    sa.UniqueConstraint('razorpay_payment_id'),
    sa.UniqueConstraint('stripe_payment_intent_id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_table('tenant_collaboration_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('max_workspaces', sa.Integer(), nullable=False),
    sa.Column('max_channels_per_workspace', sa.Integer(), nullable=False),
    sa.Column('max_workspace_members', sa.Integer(), nullable=False),
    sa.Column('max_storage_mb', sa.Integer(), nullable=False),
    sa.Column('workspace_enabled', sa.Boolean(), nullable=False),
    sa.Column('channel_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_collaboration_settings_org', 'tenant_collaboration_settings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tenant_collaboration_settings_id'), 'tenant_collaboration_settings', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_collaboration_settings_organization_id'), 'tenant_collaboration_settings', ['organization_id'], unique=True)
    op.create_table('tenant_collaboration_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('workspace_count', sa.Integer(), nullable=False),
    sa.Column('channel_count', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('storage_used_mb', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_collaboration_usage_org', 'tenant_collaboration_usage', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tenant_collaboration_usage_id'), 'tenant_collaboration_usage', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_collaboration_usage_organization_id'), 'tenant_collaboration_usage', ['organization_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_org_role', 'users', ['organization_id', 'role'], unique=False)
    op.create_index('idx_user_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_entity_type_entity_id', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_activity_user_id_created_at', 'activity_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('approval_delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegator_id', sa.Integer(), nullable=False),
    sa.Column('delegatee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delegatee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_delegations_delegatee_id'), 'approval_delegations', ['delegatee_id'], unique=False)
    op.create_index(op.f('ix_approval_delegations_delegator_id'), 'approval_delegations', ['delegator_id'], unique=False)
    op.create_index(op.f('ix_approval_delegations_end_date'), 'approval_delegations', ['end_date'], unique=False)
    op.create_index(op.f('ix_approval_delegations_id'), 'approval_delegations', ['id'], unique=False)
    op.create_index(op.f('ix_approval_delegations_is_active'), 'approval_delegations', ['is_active'], unique=False)
    op.create_index(op.f('ix_approval_delegations_start_date'), 'approval_delegations', ['start_date'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sla_status', sa.String(length=50), nullable=True),
    sa.Column('sla_due_time', sa.DateTime(), nullable=True),
    sa.Column('is_escalated', sa.Boolean(), nullable=False),
    sa.Column('current_escalation_to', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_escalation_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_requested_by_status', 'approvals', ['requested_by', 'status'], unique=False)
    op.create_index('idx_approval_status_current_level', 'approvals', ['status', 'current_level'], unique=False)
    op.create_index(op.f('ix_approvals_created_at'), 'approvals', ['created_at'], unique=False)
    op.create_index(op.f('ix_approvals_current_escalation_to'), 'approvals', ['current_escalation_to'], unique=False)
    op.create_index(op.f('ix_approvals_current_level'), 'approvals', ['current_level'], unique=False)
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_index(op.f('ix_approvals_is_escalated'), 'approvals', ['is_escalated'], unique=False)
    op.create_index(op.f('ix_approvals_requested_by'), 'approvals', ['requested_by'], unique=False)
    op.create_index(op.f('ix_approvals_sla_due_time'), 'approvals', ['sla_due_time'], unique=False)
    op.create_index(op.f('ix_approvals_sla_status'), 'approvals', ['sla_status'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_data', sa.Text(), nullable=True),
    sa.Column('new_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_module_record', 'audit_logs', ['module_name', 'record_id'], unique=False)
    op.create_index('idx_audit_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_module_name'), 'audit_logs', ['module_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('task_notifications', sa.Boolean(), nullable=False),
    sa.Column('approval_notifications', sa.Boolean(), nullable=False),
    sa.Column('escalation_notifications', sa.Boolean(), nullable=False),
    sa.Column('document_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_notification_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('sla_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('allowed_hours', sa.Integer(), nullable=False),
    sa.Column('escalation_enabled', sa.Boolean(), nullable=False),
    sa.Column('escalation_after_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_rules_id'), 'sla_rules', ['id'], unique=False)
    op.create_table('tenant_onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('onboarding_status', sa.String(length=20), nullable=False),
    sa.Column('default_workspace_created', sa.Boolean(), nullable=False),
    sa.Column('settings_created', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_onboarding_status', 'tenant_onboarding', ['onboarding_status'], unique=False)
    op.create_index(op.f('ix_tenant_onboarding_id'), 'tenant_onboarding', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_onboarding_organization_id'), 'tenant_onboarding', ['organization_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_workspace_org_slug')
    )
    op.create_index('idx_workspace_org_archived', 'workspaces', ['organization_id', 'is_archived'], unique=False)
    op.create_index(op.f('ix_workspaces_created_by'), 'workspaces', ['created_by'], unique=False)
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_table('approval_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('MEDICAL_CERTIFICATE', 'INVOICE', 'QUOTATION', 'LICENSE', 'ESTIMATE', 'OTHER', name='approval_document_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_documents_approval_id'), 'approval_documents', ['approval_id'], unique=False)
    op.create_index(op.f('ix_approval_documents_created_at'), 'approval_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_documents_id'), 'approval_documents', ['id'], unique=False)
    op.create_index(op.f('ix_approval_documents_organization_id'), 'approval_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_approval_documents_uploaded_by'), 'approval_documents', ['uploaded_by'], unique=False)
    op.create_table('approval_escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('escalated_from', sa.Integer(), nullable=False),
    sa.Column('escalated_to', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['escalated_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_escalations_id'), 'approval_escalations', ['id'], unique=False)
    op.create_table('approval_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('action_by', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_history_approval_id_created_at', 'approval_history', ['approval_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_approval_history_action_by'), 'approval_history', ['action_by'], unique=False)
    op.create_index(op.f('ix_approval_history_approval_id'), 'approval_history', ['approval_id'], unique=False)
    op.create_index(op.f('ix_approval_history_created_at'), 'approval_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_history_id'), 'approval_history', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='projectpriority'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('sla_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('sla_rule_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('breach_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sla_rule_id'], ['sla_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_tracking_id'), 'sla_tracking', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_index(op.f('ix_teams_workspace_id'), 'teams', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_index('idx_workspace_member_user_active', 'workspace_members', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_workspace_member_workspace_active', 'workspace_members', ['workspace_id', 'is_active'], unique=False)
    op.create_index('idx_workspace_member_workspace_role', 'workspace_members', ['workspace_id', 'role'], unique=False)
    op.create_index(op.f('ix_workspace_members_id'), 'workspace_members', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_members_is_active'), 'workspace_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_workspace_members_role'), 'workspace_members', ['role'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_channel_workspace_name')
    )
    op.create_index('idx_channel_org_workspace', 'channels', ['organization_id', 'workspace_id'], unique=False)
    op.create_index('idx_channel_workspace_archived', 'channels', ['workspace_id', 'is_archived'], unique=False)
    op.create_index('idx_channel_workspace_type', 'channels', ['workspace_id', 'channel_type'], unique=False)
    op.create_index(op.f('ix_channels_channel_type'), 'channels', ['channel_type'], unique=False)
    op.create_index(op.f('ix_channels_created_by'), 'channels', ['created_by'], unique=False)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_organization_id'), 'channels', ['organization_id'], unique=False)
    op.create_index(op.f('ix_channels_project_id'), 'channels', ['project_id'], unique=False)
    op.create_index(op.f('ix_channels_workspace_id'), 'channels', ['workspace_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='meetingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_organization_id'), 'meetings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meetings_project_id'), 'meetings', ['project_id'], unique=False)
    op.create_table('project_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('REQUIREMENT', 'DESIGN', 'TEST', 'RELEASE', 'OTHER', name='projectdocumenttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_documents_id'), 'project_documents', ['id'], unique=False)
    op.create_index(op.f('ix_project_documents_organization_id'), 'project_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_project_documents_project_id'), 'project_documents', ['project_id'], unique=False)
    op.create_table('project_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_teams_id'), 'project_teams', ['id'], unique=False)
    op.create_index(op.f('ix_project_teams_organization_id'), 'project_teams', ['organization_id'], unique=False)
    op.create_index(op.f('ix_project_teams_project_id'), 'project_teams', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_teams_team_id'), 'project_teams', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('LEAD', 'MEMBER', 'VIEWER', name='teammemberrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_organization_id'), 'team_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('ai_meeting_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_meeting_summaries_id'), 'ai_meeting_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_ai_meeting_summaries_meeting_id'), 'ai_meeting_summaries', ['meeting_id'], unique=True)
    op.create_index(op.f('ix_ai_meeting_summaries_organization_id'), 'ai_meeting_summaries', ['organization_id'], unique=False)
    op.create_table('channel_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='uq_channel_member')
    )
    op.create_index('idx_channel_member_channel_joined', 'channel_members', ['channel_id', 'joined_at'], unique=False)
    op.create_index('idx_channel_member_channel_role', 'channel_members', ['channel_id', 'role'], unique=False)
    op.create_index('idx_channel_member_channel_user', 'channel_members', ['channel_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_channel_members_channel_id'), 'channel_members', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_members_id'), 'channel_members', ['id'], unique=False)
    op.create_index(op.f('ix_channel_members_role'), 'channel_members', ['role'], unique=False)
    op.create_index(op.f('ix_channel_members_user_id'), 'channel_members', ['user_id'], unique=False)
    op.create_table('meeting_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance_status', sa.Enum('INVITED', 'ACCEPTED', 'DECLINED', 'TENTATIVE', name='attendancestatus'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_attendees_id'), 'meeting_attendees', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_meeting_id'), 'meeting_attendees', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_organization_id'), 'meeting_attendees', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_user_id'), 'meeting_attendees', ['user_id'], unique=False)
    op.create_table('meeting_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_notes_id'), 'meeting_notes', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_notes_meeting_id'), 'meeting_notes', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_notes_organization_id'), 'meeting_notes', ['organization_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'review', 'done', name='task_status'), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('sla_status', sa.String(length=50), nullable=True),
    sa.Column('sla_due_time', sa.DateTime(), nullable=True),
    sa.Column('is_sla_breached', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_assigned_to_status', 'tasks', ['assigned_to_id', 'status'], unique=False)
    op.create_index('idx_task_created_by_status', 'tasks', ['created_by_id', 'status'], unique=False)
    op.create_index('idx_task_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_task_status_updated_at', 'tasks', ['status', 'updated_at'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tasks_channel_id'), 'tasks', ['channel_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_is_sla_breached'), 'tasks', ['is_sla_breached'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_sla_due_time'), 'tasks', ['sla_due_time'], unique=False)
    op.create_index(op.f('ix_tasks_sla_status'), 'tasks', ['sla_status'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_team_id'), 'tasks', ['team_id'], unique=False)
    op.create_index(op.f('ix_tasks_updated_at'), 'tasks', ['updated_at'], unique=False)
    op.create_index(op.f('ix_tasks_workspace_id'), 'tasks', ['workspace_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_task_id_created_at', 'comments', ['task_id', 'created_at'], unique=False)
    op.create_index('idx_comment_user_id_created_at', 'comments', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_task_id_version', 'documents', ['task_id', 'version'], unique=False)
    op.create_index('idx_document_uploaded_by_created_at', 'documents', ['uploaded_by', 'created_at'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_task_id'), 'documents', ['task_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_history_task_id_changed_at', 'task_history', ['task_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_task_history_changed_at'), 'task_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_task_history_changed_by'), 'task_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_task_history_id'), 'task_history', ['id'], unique=False)
    op.create_index(op.f('ix_task_history_task_id'), 'task_history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_history_task_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_changed_by'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_changed_at'), table_name='task_history')
    op.drop_index('idx_task_history_task_id_changed_at', table_name='task_history')
    op.drop_table('task_history')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_task_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index('idx_document_uploaded_by_created_at', table_name='documents')
    op.drop_index('idx_document_task_id_version', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index('idx_comment_user_id_created_at', table_name='comments')
    op.drop_index('idx_comment_task_id_created_at', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_tasks_workspace_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_updated_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_team_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_sla_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_sla_due_time'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_sla_breached'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_channel_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_index('idx_task_status_updated_at', table_name='tasks')
    op.drop_index('idx_task_due_date', table_name='tasks')
    op.drop_index('idx_task_created_by_status', table_name='tasks')
    op.drop_index('idx_task_assigned_to_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_meeting_notes_organization_id'), table_name='meeting_notes')
    op.drop_index(op.f('ix_meeting_notes_meeting_id'), table_name='meeting_notes')
    op.drop_index(op.f('ix_meeting_notes_id'), table_name='meeting_notes')
    op.drop_table('meeting_notes')
    op.drop_index(op.f('ix_meeting_attendees_user_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_organization_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_meeting_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_id'), table_name='meeting_attendees')
    op.drop_table('meeting_attendees')
    op.drop_index(op.f('ix_channel_members_user_id'), table_name='channel_members')
    op.drop_index(op.f('ix_channel_members_role'), table_name='channel_members')
    op.drop_index(op.f('ix_channel_members_id'), table_name='channel_members')
    op.drop_index(op.f('ix_channel_members_channel_id'), table_name='channel_members')
    op.drop_index('idx_channel_member_channel_user', table_name='channel_members')
    op.drop_index('idx_channel_member_channel_role', table_name='channel_members')
    op.drop_index('idx_channel_member_channel_joined', table_name='channel_members')
    op.drop_table('channel_members')
    op.drop_index(op.f('ix_ai_meeting_summaries_organization_id'), table_name='ai_meeting_summaries')
    op.drop_index(op.f('ix_ai_meeting_summaries_meeting_id'), table_name='ai_meeting_summaries')
    op.drop_index(op.f('ix_ai_meeting_summaries_id'), table_name='ai_meeting_summaries')
    op.drop_table('ai_meeting_summaries')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_organization_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_project_teams_team_id'), table_name='project_teams')
    op.drop_index(op.f('ix_project_teams_project_id'), table_name='project_teams')
    op.drop_index(op.f('ix_project_teams_organization_id'), table_name='project_teams')
    op.drop_index(op.f('ix_project_teams_id'), table_name='project_teams')
    op.drop_table('project_teams')
    op.drop_index(op.f('ix_project_documents_project_id'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_organization_id'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_id'), table_name='project_documents')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_meetings_project_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_organization_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_channels_workspace_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_project_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_organization_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_created_by'), table_name='channels')
    op.drop_index(op.f('ix_channels_channel_type'), table_name='channels')
    op.drop_index('idx_channel_workspace_type', table_name='channels')
    op.drop_index('idx_channel_workspace_archived', table_name='channels')
    op.drop_index('idx_channel_org_workspace', table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_role'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_is_active'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_id'), table_name='workspace_members')
    op.drop_index('idx_workspace_member_workspace_role', table_name='workspace_members')
    op.drop_index('idx_workspace_member_workspace_active', table_name='workspace_members')
    op.drop_index('idx_workspace_member_user_active', table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_teams_workspace_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sla_tracking_id'), table_name='sla_tracking')
    op.drop_table('sla_tracking')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_approval_history_id'), table_name='approval_history')
    op.drop_index(op.f('ix_approval_history_created_at'), table_name='approval_history')
    op.drop_index(op.f('ix_approval_history_approval_id'), table_name='approval_history')
    op.drop_index(op.f('ix_approval_history_action_by'), table_name='approval_history')
    op.drop_index('idx_approval_history_approval_id_created_at', table_name='approval_history')
    op.drop_table('approval_history')
    op.drop_index(op.f('ix_approval_escalations_id'), table_name='approval_escalations')
    op.drop_table('approval_escalations')
    op.drop_index(op.f('ix_approval_documents_uploaded_by'), table_name='approval_documents')
    op.drop_index(op.f('ix_approval_documents_organization_id'), table_name='approval_documents')
    op.drop_index(op.f('ix_approval_documents_id'), table_name='approval_documents')
    op.drop_index(op.f('ix_approval_documents_created_at'), table_name='approval_documents')
    op.drop_index(op.f('ix_approval_documents_approval_id'), table_name='approval_documents')
    op.drop_table('approval_documents')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_created_by'), table_name='workspaces')
    op.drop_index('idx_workspace_org_archived', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_tenant_onboarding_organization_id'), table_name='tenant_onboarding')
    op.drop_index(op.f('ix_tenant_onboarding_id'), table_name='tenant_onboarding')
    op.drop_index('idx_tenant_onboarding_status', table_name='tenant_onboarding')
    op.drop_table('tenant_onboarding')
    op.drop_index(op.f('ix_sla_rules_id'), table_name='sla_rules')
    op.drop_table('sla_rules')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notification_user_id_is_read', table_name='notifications')
    op.drop_index('idx_notification_user_id_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_index('idx_audit_user_created', table_name='audit_logs')
    op.drop_index('idx_audit_org_created', table_name='audit_logs')
    op.drop_index('idx_audit_module_record', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_sla_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_sla_due_time'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_requested_by'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_is_escalated'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_current_level'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_current_escalation_to'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_created_at'), table_name='approvals')
    op.drop_index('idx_approval_status_current_level', table_name='approvals')
    op.drop_index('idx_approval_requested_by_status', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_approval_delegations_start_date'), table_name='approval_delegations')
    op.drop_index(op.f('ix_approval_delegations_is_active'), table_name='approval_delegations')
    op.drop_index(op.f('ix_approval_delegations_id'), table_name='approval_delegations')
    op.drop_index(op.f('ix_approval_delegations_end_date'), table_name='approval_delegations')
    op.drop_index(op.f('ix_approval_delegations_delegator_id'), table_name='approval_delegations')
    op.drop_index(op.f('ix_approval_delegations_delegatee_id'), table_name='approval_delegations')
    op.drop_table('approval_delegations')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_index('idx_activity_user_id_created_at', table_name='activity_logs')
    op.drop_index('idx_activity_entity_type_entity_id', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_role_active', table_name='users')
    op.drop_index('idx_user_org_role', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenant_collaboration_usage_organization_id'), table_name='tenant_collaboration_usage')
    op.drop_index(op.f('ix_tenant_collaboration_usage_id'), table_name='tenant_collaboration_usage')
    op.drop_index('idx_tenant_collaboration_usage_org', table_name='tenant_collaboration_usage')
    op.drop_table('tenant_collaboration_usage')
    op.drop_index(op.f('ix_tenant_collaboration_settings_organization_id'), table_name='tenant_collaboration_settings')
    op.drop_index(op.f('ix_tenant_collaboration_settings_id'), table_name='tenant_collaboration_settings')
    op.drop_index('idx_tenant_collaboration_settings_org', table_name='tenant_collaboration_settings')
    op.drop_table('tenant_collaboration_settings')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index('idx_organization_status', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
