"""add updated_by to task

Revision ID: ff98044ef74c
Revises: be20113a75b1
Create Date: 2026-04-27 15:57:42.121810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff98044ef74c'
down_revision: Union[str, Sequence[str], None] = 'be20113a75b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect_name = bind.dialect.name

    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('updated_by', sa.Integer(), nullable=True))
    if dialect_name == 'postgresql':
        op.execute(
            """
            DO $$
            BEGIN
                CREATE TYPE task_status AS ENUM ('todo', 'in_progress', 'review', 'done');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
            """
        )
        op.execute(
            "ALTER TABLE tasks ALTER COLUMN status TYPE task_status "
            "USING status::task_status"
        )
    else:
        op.alter_column('tasks', 'status',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Enum('todo', 'in_progress', 'review', 'done', name='task_status'),
                   existing_nullable=True)
    op.create_foreign_key('fk_tasks_updated_by_users', 'tasks', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect_name = bind.dialect.name

    op.drop_constraint('fk_tasks_updated_by_users', 'tasks', type_='foreignkey')
    if dialect_name == 'postgresql':
        op.execute(
            "ALTER TABLE tasks ALTER COLUMN status TYPE varchar "
            "USING status::text"
        )
        op.execute("DROP TYPE IF EXISTS task_status")
    else:
        op.alter_column('tasks', 'status',
                   existing_type=sa.Enum('todo', 'in_progress', 'review', 'done', name='task_status'),
                   type_=sa.VARCHAR(),
                   existing_nullable=True)
    op.drop_column('tasks', 'updated_by')
    op.drop_table('task_history')
    # ### end Alembic commands ###
